// @ts-check
import { createHash } from 'node:crypto'
import { readdir, readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

/**
 * Writes dist/_headers (Cloudflare Pages) after the build: security headers for every page and a
 * Content-Security-Policy that allows exactly the inline scripts Astro emitted (by their sha256), so no
 * 'unsafe-inline' for scripts. Rebuilt on every build: never edit dist/_headers by hand.
 */

const EXTERNAL_SCRIPTS = [
    'https://static.cloudflareinsights.com', // Cloudflare Web Analytics
]

/** Executable inline scripts; JSON-LD and other data blocks are not subject to script-src. */
const INLINE_SCRIPT = /<script(?![^>]*\bsrc=)([^>]*)>([\s\S]*?)<\/script>/g
const EXECUTABLE_TYPE = /\btype=["']?(module|text\/javascript|application\/javascript)["']?/

/** @param {string} dir */
async function htmlFiles(dir) {
    const entries = await readdir(dir, { withFileTypes: true, recursive: true })
    return entries.filter(entry => entry.isFile() && entry.name.endsWith('.html')).map(entry => join(entry.parentPath, entry.name))
}

/** @param {Set<string>} hashes */
export function csp(hashes) {
    return [
        "default-src 'self'",
        `script-src 'self' ${[...hashes].sort().map(hash => `'${hash}'`).join(' ')} ${EXTERNAL_SCRIPTS.join(' ')}`,
        // Astro's scoped styles and style attributes are inline
        "style-src 'self' 'unsafe-inline'",
        "img-src 'self' data:",
        "font-src 'self'",
        // Accedi checks https://<slug>.chicomanda.com/api/health; Web Analytics sends its beacon
        "connect-src 'self' https://*.chicomanda.com https://cloudflareinsights.com",
        "frame-src 'none'",
        "form-action 'self'",
        "base-uri 'self'",
        "object-src 'none'",
        "frame-ancestors 'none'",
        'upgrade-insecure-requests',
    ].join('; ')
}

/**
 * @param {{ indexable: boolean }} options  `indexable` false: every response (pages, images, files) carries
 *   `X-Robots-Tag: noindex`, besides the pages' robots meta tag
 * @returns {import('astro').AstroIntegration}
 */
export default function securityHeaders({ indexable }) {
    return {
        name: 'security-headers',
        hooks: {
            'astro:build:done': async ({ dir, logger }) => {
                const out = fileURLToPath(dir)
                const hashes = new Set()
                for (const file of await htmlFiles(out)) {
                    const html = await readFile(file, 'utf8')
                    for (const [, attributes, body] of html.matchAll(INLINE_SCRIPT)) {
                        if (/\btype=/.test(attributes) && !EXECUTABLE_TYPE.test(attributes)) continue
                        hashes.add(`sha256-${createHash('sha256').update(body).digest('base64')}`)
                    }
                }

                const headers = `# Generated by integrations/security-headers.mjs at build time: do not edit.

/*
  Content-Security-Policy: ${csp(hashes)}
  Strict-Transport-Security: max-age=31536000
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=(), payment=(), usb=()
  Cross-Origin-Opener-Policy: same-origin
${indexable ? '' : '  X-Robots-Tag: noindex, nofollow\n'}
/_astro/*
  Cache-Control: public, max-age=31536000, immutable

# The pages.dev addresses (production and preview deployments) and the public preview
# vetrina.chicomanda.com are never indexed, also after the cutover to chicomanda.com.
https://:project.pages.dev/*
  X-Robots-Tag: noindex
https://vetrina.chicomanda.com/*
  X-Robots-Tag: noindex
https://:version.:project.pages.dev/*
  X-Robots-Tag: noindex
`
                await writeFile(join(out, '_headers'), headers)
                logger.info(`_headers written, ${hashes.size} inline script hash(es) in the CSP`)
            },
        },
    }
}
